x-app: &app
  build: .
  restart: on-failure
  env_file:
    - path: .env
      required: false

services:
  coordinator:
    <<: *app
    command: python -m workerz.coordinator
    ports: ["7777:7777"]
    environment:
      WORKERZ_TCP_HOST: "0.0.0.0"
      WORKERZ_TCP_PORT: "7777"
      WORKERZ_COORDINATOR_LOG: /app/logs/coordinator.log
    volumes:
      - ./logs:/app/logs

  dashboard:
    <<: *app
    command: python -m workerz.dashboard
    ports: ["8080:8080"]
    environment:
      WORKERZ_DASHBOARD_PORT: "8080"
      WORKERZ_COORDINATOR_HOST: coordinator
      WORKERZ_COORDINATOR_TCP: "7777"
      WORKERZ_DASHBOARD_LOG: /app/logs/dashboard.log
    volumes:
      - ./logs:/app/logs
    depends_on: [coordinator]

  worker:
    <<: *app
    command: python -m workerz.worker /app/example_tasks.py
    environment:
      WORKERZ_LABELS: add,slow,fail,buggy
      WORKERZ_COORDINATOR_HOST: coordinator
      WORKERZ_COORDINATOR_TCP: "7777"
      WORKERZ_WORKER_LOG: /app/logs/worker.log
    volumes:
      - ./logs:/app/logs
    depends_on: [coordinator]

  submitter:
    <<: *app
    command: python /app/submitter.py
    environment:
      WORKERZ_COORDINATOR_HOST: coordinator
      WORKERZ_COORDINATOR_TCP: "7777"
      WORKERZ_SDK_LOG: /app/logs/sdk.log
    volumes:
      - ./logs:/app/logs
    depends_on: [coordinator]
