[build-system]
requires      = ["setuptools>=72"]
build-backend = "setuptools.build_meta"

[project]
name            = "workerz"
dynamic         = ["version"]
description     = "Better Workers."
requires-python = ">=3.11"
dependencies    = []
readme = "README.md"

[project.optional-dependencies]
coordinator = ["loguru>=0.7", "python-dotenv>=1.0", "msgspec>=0.18"]
dashboard   = ["loguru>=0.7", "python-dotenv>=1.0", "starlette>=0.41", "uvicorn>=0.29", "msgspec>=0.18"]
worker      = ["loguru>=0.7", "python-dotenv>=1.0", "msgspec>=0.18"]
sdk         = ["loguru>=0.7", "python-dotenv>=1.0", "msgspec>=0.18"]
full        = ["workerz[coordinator]", "workerz[dashboard]", "workerz[worker]", "workerz[sdk]"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"workerz.dashboard" = ["index.html"]

[tool.setuptools.dynamic]
version = {attr = "workerz.__version__"}
